// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClGjRKQIdwBEsDLyQn3YoBSSwBx_XECCk',
    appId: '1:161329955341:web:9b4d2720a6b505994b4b44',
    messagingSenderId: '161329955341',
    projectId: 'postapp-b1854',
    authDomain: 'postapp-b1854.firebaseapp.com',
    storageBucket: 'postapp-b1854.firebasestorage.app',
    measurementId: 'G-B0SP7KXZ6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBNqcYi63aPnA5i2Zp6TKsU86S5OOYdjE',
    appId: '1:161329955341:android:a12624ecbbbe673a4b4b44',
    messagingSenderId: '161329955341',
    projectId: 'postapp-b1854',
    storageBucket: 'postapp-b1854.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCabylT0PeWEscp1ZbjwY21xhkvquq22SE',
    appId: '1:161329955341:ios:9d3fcb96dd291ee74b4b44',
    messagingSenderId: '161329955341',
    projectId: 'postapp-b1854',
    storageBucket: 'postapp-b1854.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCabylT0PeWEscp1ZbjwY21xhkvquq22SE',
    appId: '1:161329955341:ios:9d3fcb96dd291ee74b4b44',
    messagingSenderId: '161329955341',
    projectId: 'postapp-b1854',
    storageBucket: 'postapp-b1854.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClGjRKQIdwBEsDLyQn3YoBSSwBx_XECCk',
    appId: '1:161329955341:web:0a75872c322866b04b4b44',
    messagingSenderId: '161329955341',
    projectId: 'postapp-b1854',
    authDomain: 'postapp-b1854.firebaseapp.com',
    storageBucket: 'postapp-b1854.firebasestorage.app',
    measurementId: 'G-3NS8FQ3R0T',
  );
}
